# Generated by Django 2.2 on 2022-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_mymodelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=128)),
                ('last_name', models.CharField(default=None, max_length=128)),
                ('username', models.CharField(default=None, max_length=128)),
                ('password', models.CharField(default=None, max_length=128)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
