# Generated by Django 2.2 on 2022-05-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_area_articulo_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Figura',
        ),
    ]
