# Generated by Django 2.2 on 2022-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220510_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='art',
            field=models.ManyToManyField(help_text='Seleccione un articulo que desee ver', to='app.Articulo'),
        ),
    ]
