# Generated by Django 2.2 on 2022-05-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_figura_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='area',
        ),
        migrations.AddField(
            model_name='articulo',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Area'),
        ),
        migrations.RemoveField(
            model_name='figura',
            name='art',
        ),
        migrations.AddField(
            model_name='figura',
            name='art',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Articulo'),
        ),
    ]
