# Generated by Django 2.2 on 2022-05-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220510_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='author',
        ),
    ]
