# Generated by Django 2.2 on 2022-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_articulo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Area'),
        ),
    ]
