# Generated by Django 2.2 on 2022-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_figura_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figura',
            options={'ordering': ['last_name']},
        ),
    ]
