# Generated by Django 2.2 on 2022-05-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220511_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figura',
            options={'ordering': ['last_name']},
        ),
    ]
