# Generated by Django 2.2 on 2022-05-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220526_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figura',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Area'),
        ),
    ]
