# Generated by Django 2.2 on 2022-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220526_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='area',
        ),
        migrations.AddField(
            model_name='figura',
            name='area',
            field=models.ManyToManyField(to='app.Area'),
        ),
    ]
