# Generated by Django 3.2 on 2022-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='question',
        ),
        migrations.AddField(
            model_name='categoria',
            name='question',
            field=models.ManyToManyField(to='app.QuesModel'),
        ),
    ]
