# Generated by Django 3.2 on 2022-05-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220528_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='question',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria'),
        ),
    ]
