# Generated by Django 3.2 on 2022-05-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figura',
            name='area',
        ),
        migrations.AddField(
            model_name='figura',
            name='area',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
