# Generated by Django 3.2 on 2022-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_curiosidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('respuesta', models.CharField(max_length=200, null=True)),
                ('categoria', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=128, null=True)),
                ('apellido', models.CharField(default=None, max_length=128, null=True)),
                ('nombre_usuario', models.CharField(default=None, max_length=128, unique=True)),
                ('contrasena', models.CharField(default=None, max_length=128, null=True)),
                ('email', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'ordering': ('apellido', 'nombre'),
            },
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='figura',
            options={'ordering': ['apellido']},
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='curiosidad',
            old_name='summary',
            new_name='resumen',
        ),
        migrations.RenameField(
            model_name='curiosidad',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='figura',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='figura',
            old_name='date_of_death',
            new_name='fecha_de_fallecimiento',
        ),
        migrations.RenameField(
            model_name='figura',
            old_name='date_of_birth',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='summary',
            new_name='resumen',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='figura',
            name='first_name',
        ),
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='resumen',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='figura',
            name='nombre',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
