# Generated by Django 3.2 on 2022-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='nombre_protagonista',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
