# Generated by Django 3.2 on 2022-06-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_noticia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
    ]
