# Generated by Django 3.2 on 2022-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20220609_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiosidad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
